# Generated by Django 5.1.3 on 2024-11-22 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('picture', models.BinaryField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('default_view', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divan.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divan.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divan.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divan.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divan.task')),
            ],
        ),
    ]
